@url = http://localhost:3733

### GET ALL SKILLS
GET {{url}}/skills

### ADD A SKILL
POST {{url}}/skills
content-type: application/json

{
	"idCode":"777",
	"name":"nnn",
	"url":"uuu",
	"description":"ddd"
}